version: '3'

services:
  djangoapp:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
    networks:
      - app_network

  nginx:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/static
    depends_on:
      - djangoapp
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  static_volume:
